apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-001
  labels:
    app: mongodb-service-001
spec:
  selector:
    app: mongodb-service-001
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
