apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb-statefulset
  serviceName: mongodb-service-001
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb-statefulset
    spec:
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongodb-statefulset
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pv
              mountPath: /data/db 
