apiVersion: v1
kind: Pod
metadata:
  name: db 
spec:
  containers:
  - image: mongo:4.0.6
    name: mongodb
    # Mount as volume 
    volumeMounts:
    - name: data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: data
    # Declare the PVC to use for the volume
    persistentVolumeClaim:
      claimName: db-data


# kubectl exec db -it -- mongo testdb --quiet --eval \
#  'db.messages.insert({"message": "I was here"}); db.messages.findOne().message'
  
# kubectl delete -f db.yaml

# kubectl create -f db.yaml

# kubectl exec db -it -- mongo testdb --quiet --eval 'db.messages.findOne().message'