apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo_data"
