apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
             
            