apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx1
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine   
      ports:
        - containerPort: 80
      resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
      livenessProbe: # Define live ness probes 
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15 # initial delay wait for 15 seconds
        periodSeconds: 5 # Periodic probe checks 
        timeoutSeconds: 2 
        failureThreshold: 1 # Allow 1 failure before failing Pod
      readinessProbe: # Define readiness probes
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2 # wait for 2 seconds 
        periodSeconds: 5 # Check every 5 seconds



            