apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx1
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine   
      ports:
        - containerPort: 80
      resources:
          limits:
            memory: "200Mi"
            cpu: "20m"
             
            